server:
  port: 8080
spring:
  application:
    name: "User"
  devtools:
    add-properties: false
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:27017/admin"
      auto-index-creation: true
  kafka:
    topic: "put-logs"
    boostrap-servers: "${KAFKA_BOOSTRAP_SERVERS}"
cache:
  ttl: 120
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
